155 t login web handler
Arc-i-Tech/Arc-i-Tech.github.io pull request #180
Opened 2024-10-30 17:10 UTC by dipikakoli26

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
- *Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*
- Go throw [Pull request guidelines](./../pull-request-guidelines.md) if you are not aware of them.

## Please check if the PR fulfills these requirements
- [ ] My code follows the code style of this project.
- [ ] The commit message follows our guidelines.
- [ ] Tests for the changes have been added (for bug fixes/features).
- [ ] Have you successfully run tests with your changes locally?
- [ ] Docs have been added/updated (for bug fixes/features).

## What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

## What is the current behavior?** (You can also link to an open issue here)

## What is the new behavior (if this is a feature change)?

## Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

## Test Plan

## Closing issues

2024-10-31 11:24 UTC, ajayg2808 commented
Follow **Pull request template**.
Title and description of pull request must be proper, concise and brief overview about what, why and how the task is completed and how to validate it.

2024-10-31 11:25 UTC, ajayg2808 commented
Do not add labels to pull request until and unless it do not have issue for it.

2024-11-13 05:02 UTC, ajstyle2410 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserService.java
> +    private UserRepository userRepository;
this class not present in a package inside

2024-11-13 05:05 UTC, ajstyle2410 requested changes

2024-11-13 05:05 UTC, ajstyle2410 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserService.java
> +    private UserRepository userRepository;
this class not present in a package inside

2024-11-13 05:05 UTC, ajstyle2410 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserService.java
> +            throw new UserAlreadyExistsException("Username " + userAuth.getUsername() + " already exists");
UserAlreadyExistsException are  not recognize the project inside

2024-11-13 05:05 UTC, ajstyle2410 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserService.java
> +        userAuthRepository.save(userAuth);
save method not work properly

2024-11-13 05:05 UTC, ajstyle2410 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/UserController.java
> +        return userService.findByUserAndPassword(userAuth);
findByUserAndPassword are not present in a  service inside

2024-12-05 03:40 UTC, ajstyle2410 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserService.java
> +    private UserRepository userRepository;
resolved it

2024-12-13 11:27 UTC, ajayg2808 commented
@ajstyle2410,

- [x] Resolve merge conflicts.
- [x] Update PR template 

Let me know, once it is done.

2024-12-14 06:36 UTC, ajstyle2410 commented
> @ajstyle2410,
> 
> * [ ]  Resolve merge conflicts.
> * [x]  Update PR template
> 
> Let me know, once it is done.

Conflict resolved

2024-12-15 12:37 UTC, ajayg2808 commented
> > @ajstyle2410,
> > 
> > * [x]   Resolve merge conflicts.
> > * [x]   Update PR template
> > 
> > Let me know, once it is done.
> 
> Conflict resolved

PR template is not updated yet.
Your PR still is linked to project. I am not going to review it.

2024-12-15 15:39 UTC, ajstyle2410 commented
@ajayg2808  update the pull request changes the pull request  issue number

2024-12-17 12:48 UTC, ajayg2808 approved these changes

2024-12-17 12:51 UTC, merged