User Registration Web Handler
Arc-i-Tech/Arc-i-Tech.github.io pull request #209
Opened 2024-12-19 15:20 UTC by priyapal2000

Add user details and generate the password.

### To be removed when PR is created
**:memo: IMPORTANT: Please do not create a Pull Request without creating an issue first.**
- _Any changes needs to be discussed before proceeding, failure to do so may result in the rejection of the pull request._
- _Go throw [Pull request guidelines](./../docs/guidelines/pull-request-guidelines.md) if you are not aware of them._

## Pull Request Title
- Short and descriptive (e.g., "Fix issue with login form validation")

## Description
- Provide a brief description of what this PR does, including the problem it solves or the feature it adds.
- Mention any dependencies or related tickets/issues.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Project Configuration
- [ ] Repository Configuration
- [ ] Documentation update - Code guide/ docs (_like, javadoc or api_)
- [ ] Other (please describe):

## Screenshots / GIFs / Media (if applicable)
- Attach relevant screenshots or GIFs to help reviewers understand the UI or UX changes.

## How Has This Been Tested?/ Test Plan
- Describe the testing that you conducted, such as unit tests, integration tests, or manual testing.
- Mention any relevant testing tools or configurations.

## Checklist:
- [ ] My code follows the project’s [coding guidelines](./../../docs/guidelines/coding-guides/). 
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code where necessary.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] I have added tests that verify the functionality of the code (if applicable).
- [ ] All new and existing tests pass.

## How to use/ enable
- Describe/ guide if any additional adaptions are necessary to use this feature/ changes.

## Additional Notes
- Add any additional information that could be useful to the reviewer.

## Closing issues
- Link any relevant issues here (e.g., `Closes #123`).

2024-12-19 18:44 UTC, priyapal2000 commented
@ajayg2808 
Please review the PR.

2024-12-24 11:33 UTC, priyapal2000 commented
@ajayg2808 
Please review the PR.

2024-12-24 12:57 UTC, ajayg2808 commented
@priyapal2000,
Do below updates:
- [x] Correct section: **How Has This Been Tested?/ Test Plan**
- [x] Mention endpoints: **How to use/ enable**
- [x] Use JSON code block for Request and Response body currently it is normal code block
- [x] Handle failure properly do not delegate it to `INTERNAL_SERVER_ERROR`
- [x] In the Request Body `enabled` is of type `boolean` and not a `int`
- [x] Assign PR

2024-12-25 04:48 UTC, priyapal2000 commented
@ajayg2808 
PR is updated

2024-12-25 09:28 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/UserRegistrationController.java
> +public class UserRegistrationController {
Class name should be `UserController`.

2024-12-25 09:41 UTC, ajayg2808 requested changes
- [x] Endpoint `/api/auth/register` is not found
- [x] Endpoint mentioned in pull request description and actual implemented endpoint is different.
- [x] Endpoint should be `/api/user/register` or `/api/user/add`

2024-12-25 09:41 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/UserRegistrationController.java
> +	@GetMapping("findByUserId/{id}")
Do not implement `Get/ Find User` API

2024-12-25 09:41 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/UserRegistrationController.java
> +	public ResponseEntity<UserAuth> createUser(@RequestBody User user) {
Change endpoint

2024-12-25 09:41 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/UserRegistrationController.java
> +	    else {
Do not create `INTERNAL_SERVER_ERROR`. Internal server error depicts system/ server failure to handle use case.

2024-12-25 09:41 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/UserRegistrationController.java
> +	        return new ResponseEntity<>(userAuth, HttpStatus.INTERNAL_SERVER_ERROR);
Return proper JSON response including proper error message "Why user not added?"

2024-12-25 09:41 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/model/PersonalDetails.java
>  	private int moNo;
Change `moNo` field to `String`

2024-12-25 09:41 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/repository/UserAuthRepository.java
Use/ Copy it from #191

2024-12-25 09:41 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/repository/UserRepository.java
Use/ Copy it from #191

2024-12-25 09:41 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserService.java
> +	public User getUserById(Long id);
Why it is needed?

2024-12-25 09:41 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserServiceImplement.java
> +public class UserServiceImplement implements UserService {
Rename class to `UserServiceImpl` and move it to package `com.arcitech.service.impl`

2024-12-25 09:41 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserServiceImplement.java
> +	private static final Logger logger = LoggerFactory.logger(UserServiceImplement.class);
Do not use logger, we are not started using it yet.

2024-12-25 09:41 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserServiceImplement.java
> +	public UserAuth addUser(User user) {
Add user must return `User` object only.

2024-12-25 09:41 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserServiceImplement.java
> +	public User getUserById(Long id) {
Not needed.

2024-12-26 14:46 UTC, priyapal2000 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/UserRegistrationController.java
> +public class UserRegistrationController {
Is done.

2024-12-26 14:50 UTC, priyapal2000 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/UserRegistrationController.java
> +	@GetMapping("findByUserId/{id}")
Use http request Post.

2024-12-26 14:53 UTC, priyapal2000 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/UserRegistrationController.java
> +	public ResponseEntity<UserAuth> createUser(@RequestBody User user) {
is done.

2024-12-26 15:23 UTC, priyapal2000 commented on Arc-i-Tech/src/main/java/com/arcitech/model/PersonalDetails.java
>  	private int moNo;
changes is done.

2024-12-26 15:43 UTC, priyapal2000 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserServiceImplement.java
> +	private static final Logger logger = LoggerFactory.logger(UserServiceImplement.class);
is done.

2024-12-26 15:43 UTC, priyapal2000 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserServiceImplement.java
> +	public User getUserById(Long id) {
ok

2024-12-26 19:52 UTC, priyapal2000 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/UserRegistrationController.java
> +	    else {
is done.

2024-12-26 19:52 UTC, priyapal2000 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/UserRegistrationController.java
> +	    else {
is done

2024-12-26 19:52 UTC, priyapal2000 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/UserRegistrationController.java
> +	        return new ResponseEntity<>(userAuth, HttpStatus.INTERNAL_SERVER_ERROR);
is done.

2024-12-26 19:55 UTC, priyapal2000 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserServiceImplement.java
> +public class UserServiceImplement implements UserService {
Done

2024-12-26 19:56 UTC, priyapal2000 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserService.java
> +	public User getUserById(Long id);
ok

2024-12-27 15:10 UTC, ajayg2808 commented
@priyapal2000,
These conversations are not resolved yet:
- [x] https://github.com/Arc-i-Tech/Arc-i-Tech.github.io/pull/209#discussion_r1897231906
- [x] https://github.com/Arc-i-Tech/Arc-i-Tech.github.io/pull/209#discussion_r1897232668
- [x] https://github.com/Arc-i-Tech/Arc-i-Tech.github.io/pull/209#discussion_r1897234032

2024-12-27 15:12 UTC, priyapal2000 commented on Arc-i-Tech/src/main/java/com/arcitech/repository/UserAuthRepository.java
it's done

2024-12-27 15:12 UTC, priyapal2000 commented on Arc-i-Tech/src/main/java/com/arcitech/repository/UserRepository.java
done.

2024-12-27 15:43 UTC, priyapal2000 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserServiceImplement.java
> +	public UserAuth addUser(User user) {
is done

2024-12-27 15:44 UTC, priyapal2000 commented
@ajayg2808 
All Conversations is resolve.

2024-12-27 16:14 UTC, priyapal2000 commented
@ajayg2808 
PR is updated .

2024-12-27 19:19 UTC, ajayg2808 approved these changes

2024-12-28 05:24 UTC, merged