Reset Password API
Arc-i-Tech/Arc-i-Tech.github.io pull request #212
Opened 2024-12-28 11:23 UTC by ajstyle2410

using email reset the password to send the link to  uesr email and create the new password

### To be removed when PR is created
**:memo: IMPORTANT: Please do not create a Pull Request without creating an issue first.**
- _Any changes needs to be discussed before proceeding, failure to do so may result in the rejection of the pull request._
- _Go throw [Pull request guidelines](./../docs/guidelines/pull-request-guidelines.md) if you are not aware of them._

## Pull Request Title
- Short and descriptive (e.g., "Fix issue with login form validation")

## Description
- Provide a brief description of what this PR does, including the problem it solves or the feature it adds.
- Mention any dependencies or related tickets/issues.

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Project Configuration
- [ ] Repository Configuration
- [ ] Documentation update - Code guide/ docs (_like, javadoc or api_)
- [ ] Other (please describe):

## Screenshots / GIFs / Media (if applicable)
- Attach relevant screenshots or GIFs to help reviewers understand the UI or UX changes.

## How Has This Been Tested?/ Test Plan
- Describe the testing that you conducted, such as unit tests, integration tests, or manual testing.
- Mention any relevant testing tools or configurations.

## Checklist:
- [ ] My code follows the project’s [coding guidelines](./../../docs/guidelines/coding-guides/). 
- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code where necessary.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] I have added tests that verify the functionality of the code (if applicable).
- [ ] All new and existing tests pass.

## How to use/ enable
- Describe/ guide if any additional adaptions are necessary to use this feature/ changes.

## Additional Notes
- Add any additional information that could be useful to the reviewer.

## Closing issues
- Link any relevant issues here (e.g., `Closes #123`).

2024-12-28 19:26 UTC, ajayg2808 commented
@ajstyle2410,
- [x] Add reviewers as per guidance 
- [x] Correct description formatting

2024-12-29 12:59 UTC, ajayg2808 requested changes
Do necessary changes

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/pom.xml
Follow code formatting

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/ForgotPasswordController.java
> +    @PostMapping("/verify_otp_and_reset_password/{username}/{otp}/{newPassword}")
OTP cannot be a path variable

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/model/User.java
> +	private String otp; // Field for OTP storage
OTP cannot be field in table

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/ForgotPasswordController.java
> +    @PostMapping("/verify_otp_and_reset_password/{username}/{otp}/{newPassword}")
Endpoint cannot be so lengthy

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/ForgotPasswordController.java
> +    @PostMapping("/generate_otp/{username}")
Generate OPT should not include username in path variable, instead use request body.

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/ForgotPasswordController.java
> +        return userService.generateOtp(username);
Verify user before generating OTP

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/exception/InvalidTokenException.java
Remove unnecessary exception handling

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/exception/UserNotFoundException.java
Remove unnecessary exception handling

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/helper/OTPGenerator.java
> +		throw new OperationNotSupportedException();
Throw Unsupported operation exception

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/helper/OTPGenerator.java
> +	private OTPGenerator() throws OperationNotSupportedException {
Do not `throws` exception

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/helper/SiteURL.java
Add proper comment for class and methods

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/model/User.java
> +	private String email;
Email must be part of person details

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/service/ForgotPasswordService.java
Where this service is used.
Do not create service for forgot password

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserService.java
> +	public ResponseEntity<Map<String, Object>> verifyOtpAndResetPassword(String username, String otp,
Service should not return ResponseEntity, it must be taken care by controller

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/service/impl/ForgotPasswordServiceImpl.java
> +	        throw new UserNotFoundException("User not found with username: " + username);
Do not throw exception from service to controller

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/service/impl/ForgotPasswordServiceImpl.java
> +public class ForgotPasswordServiceImpl implements ForgotPasswordService {
Do not use a dedicated service for forgot password, instead use auth service.

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/java/com/arcitech/service/impl/UserServiceImpl.java
> +		User user = userAuth.getUser(); // Fetch the associated User object
Do null check for UserAuth.

2024-12-29 12:59 UTC, ajayg2808 commented on Arc-i-Tech/src/main/resources/application.properties
> +#Email Configuration
Follow code formatting for comments

2024-12-30 03:09 UTC, ajstyle2410 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/ForgotPasswordController.java
> +    @PostMapping("/verify_otp_and_reset_password/{username}/{otp}/{newPassword}")
is done

2024-12-30 03:09 UTC, ajstyle2410 commented on Arc-i-Tech/src/main/java/com/arcitech/model/User.java
> +	private String otp; // Field for OTP storage
done

2024-12-30 03:09 UTC, ajstyle2410 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/ForgotPasswordController.java
> +    @PostMapping("/verify_otp_and_reset_password/{username}/{otp}/{newPassword}")
done

2024-12-30 03:09 UTC, ajstyle2410 commented on Arc-i-Tech/src/main/java/com/arcitech/controllers/ForgotPasswordController.java
> +    @PostMapping("/generate_otp/{username}")
done

2024-12-30 03:10 UTC, ajstyle2410 commented on Arc-i-Tech/src/main/java/com/arcitech/service/UserService.java
> +	public ResponseEntity<Map<String, Object>> verifyOtpAndResetPassword(String username, String otp,
done

2024-12-30 03:10 UTC, ajstyle2410 commented on Arc-i-Tech/src/main/java/com/arcitech/service/impl/ForgotPasswordServiceImpl.java
> +	        throw new UserNotFoundException("User not found with username: " + username);
done

2024-12-30 03:10 UTC, ajstyle2410 commented on Arc-i-Tech/src/main/java/com/arcitech/service/impl/ForgotPasswordServiceImpl.java
> +public class ForgotPasswordServiceImpl implements ForgotPasswordService {
done

2024-12-30 03:10 UTC, ajstyle2410 commented on Arc-i-Tech/src/main/java/com/arcitech/service/impl/UserServiceImpl.java
> +		User user = userAuth.getUser(); // Fetch the associated User object
done

2024-12-30 04:00 UTC, ajstyle2410 commented on Arc-i-Tech/pom.xml
resolved

2025-01-01 18:26 UTC, ajayg2808 commented on Arc-i-Tech/src/main/resources/application.properties
> +spring.mail.password=****
Filled with dummy values

2025-01-01 18:32 UTC, merged