basic contact us page
Arc-i-Tech/Arc-i-Tech.github.io pull request #57
Opened 2023-02-21 16:52 UTC by ajstyle2410

This is  Contact  us page using bootstrap
 closes #30

2023-02-22 14:27 UTC, ajayg2808 requested changes
- [ ] Use `main.css` and `main.js` this files are common for all pages.
- [ ] Use bootstrap icons
- [ ] Status bar not correct (Because `main.css` not included)
- [ ] `<head>` tag should be similar to `index.html`
- [ ] Check inline review (for files changed)

2023-02-22 14:27 UTC, ajayg2808 commented on css/contact_us.css
> +section {
No need to add **css** for contact us

2023-02-22 14:27 UTC, ajayg2808 commented on contact_us.html
> +                                            d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7
Replace SVG's with bootstrap icons

2023-02-22 14:27 UTC, ajayg2808 commented on contact_us.html
> +        <title>Arc-i-Tech </title>
Remove extra space from **title**

2023-02-24 03:16 UTC, ajstyle2410 commented on contact_us.html
> +                                            d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7
i am replaced svg icons

2023-02-24 18:57 UTC, ajayg2808 requested changes
1. Contact us page looks good, but white strip around is not that good looking.
    ![image](https://user-images.githubusercontent.com/34316783/221266993-0c8f77b0-c2ab-4f3d-a213-4abd22e99811.png)

2. Border in footer not working as expected in contact us page.
    ![image](https://user-images.githubusercontent.com/34316783/221267210-562f92e0-997a-40be-9e59-e650875c4b9f.png)

3. Why _index.html_ committed here?

2023-02-24 18:57 UTC, ajayg2808 commented on contact_us.html
> +        <title>Arc-i-Tech </title>
Remove extra space from title

2023-02-24 18:57 UTC, ajayg2808 commented on index.html
> +              <button class="carousel-control-prev border border-dark z-2" type="button"
Why `z-index` updated?

2023-02-24 18:57 UTC, ajayg2808 commented on index.html
> +              <button class="carousel-control-next border border-dark z-2" type="button"
Why `z-index` updated?

2023-03-24 20:28 UTC, ajayg2808 approved these changes

2023-03-24 20:36 UTC, merged